In [3]:
import numpy as np
rgb = np.array([[[255, 0, 0], [255, 255, 0], [255, 255, 255]], \
                [[255, 0, 255], [0, 255, 0], [0, 255, 255]], \
                [[0, 0, 0], [0, 255, 255], [0, 0, 255]]]) 

In [5]:
red_array = rgb[:,:,0]
red_array

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])

In [6]:
rgb[0]

array([[255,   0,   0],
       [255, 255,   0],
       [255, 255, 255]])

In [7]:
rgb[0,0,0]

255

In [8]:
rgb[0,1,0]

255

In [9]:
red_array.shape

(3, 3)

In [10]:
red_array, green_array, blue_array = np.split(rgb, 3, axis=2)
red_array

array([[[255],
        [255],
        [255]],

       [[255],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0]]])

In [11]:
red_array.shape

(3, 3, 1)

In [12]:
red_array_2D = red_array.reshape((3,3))
red_array_2D

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])