# Activity 1.01: Using NumPy to compute the *mean*, *median*, *variance*, and *standard deviation* of a dataset

In [1]:
import numpy as np

In [2]:
dataset = np.genfromtxt('../Datasets/normal_distribution.csv', delimiter=',')

In [3]:
# Print a subset of the first two rows of the dataset
print(dataset[0:2,:])

[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914
   98.80833412  96.81964892  98.56783189]
 [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
   92.65657752 105.7197853  101.23162942]]


In [7]:
# The mean of the third row
np.mean(dataset[2])

100.20466135250001

In [18]:
# Index the last element of an ndarray
dataset[-1,-1]

100.07721494

In [9]:
# Get a submatrix of the first three elements of every row of the first three column
dataset[0:3, 0:3]

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132]])

In [10]:
np.median(dataset[-1,:])

99.18748092

In [11]:
dataset[:, -3:]

array([[ 98.80833412,  96.81964892,  98.56783189],
       [ 92.65657752, 105.7197853 , 101.23162942],
       [105.95297652,  98.37481387, 106.54654286],
       [ 91.6604946 , 106.1472841 ,  95.08715803],
       [108.57980357, 100.79478953,  94.20019732],
       [ 96.2832753 , 104.60344836, 101.13442416],
       [ 95.46493436,  94.35373179, 106.83273763],
       [ 98.74767493,  97.57544275,  92.5748759 ],
       [100.85447132, 101.2226037 , 106.03868807],
       [101.72074646,  96.96851209, 103.29147111],
       [ 99.35999981,  98.87007532,  95.85284217],
       [102.62384733, 105.07475277,  97.59572169],
       [ 95.19184343,  91.32093303, 102.35313953],
       [108.09423367,  96.50342927,  99.58664719],
       [ 99.69982772, 103.05289628, 103.93383957],
       [ 96.34622848,  96.89244283,  98.07122664],
       [105.37011896,  99.07551254, 104.15899829],
       [ 98.65912661,  98.72774132, 104.70526438],
       [ 96.5937781 ,  93.04610867,  99.92159953],
       [101.83845792,  97.94046

In [20]:
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

In [21]:
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [22]:
np.var(dataset[-2:,:2])

4.674691991769191

In [16]:
np.std(dataset)

4.838197554269257

In [19]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749