# Activity 1.01: Using NumPy to compute the *mean*, *median*, *variance*, and *standard deviation* of a dataset

In [1]:
import numpy as np

In [2]:
dataset = np.genfromtxt('../Datasets/normal_distribution.csv', delimiter=',')

In [3]:
# Print a subset of the first two rows of the dataset
print(dataset[0:2,:])

[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914
   98.80833412  96.81964892  98.56783189]
 [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
   92.65657752 105.7197853  101.23162942]]


In [4]:
# The mean of the third row
np.mean(dataset[2])

100.20466135250001

In [5]:
# Index the last element of an ndarray
dataset[-1,-1]

100.07721494

In [6]:
# Get a submatrix of the first three elements of every row of the first three column
dataset[0:3, 0:3]

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132]])

In [7]:
np.median(dataset[-1,:])

99.18748092

In [8]:
dataset[:, -3:]

array([[ 98.80833412,  96.81964892,  98.56783189],
       [ 92.65657752, 105.7197853 , 101.23162942],
       [105.95297652,  98.37481387, 106.54654286],
       [ 91.6604946 , 106.1472841 ,  95.08715803],
       [108.57980357, 100.79478953,  94.20019732],
       [ 96.2832753 , 104.60344836, 101.13442416],
       [ 95.46493436,  94.35373179, 106.83273763],
       [ 98.74767493,  97.57544275,  92.5748759 ],
       [100.85447132, 101.2226037 , 106.03868807],
       [101.72074646,  96.96851209, 103.29147111],
       [ 99.35999981,  98.87007532,  95.85284217],
       [102.62384733, 105.07475277,  97.59572169],
       [ 95.19184343,  91.32093303, 102.35313953],
       [108.09423367,  96.50342927,  99.58664719],
       [ 99.69982772, 103.05289628, 103.93383957],
       [ 96.34622848,  96.89244283,  98.07122664],
       [105.37011896,  99.07551254, 104.15899829],
       [ 98.65912661,  98.72774132, 104.70526438],
       [ 96.5937781 ,  93.04610867,  99.92159953],
       [101.83845792,  97.94046

In [9]:
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

In [10]:
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [11]:
np.var(dataset[-2:,:2])

4.674691991769191

In [12]:
np.std(dataset)

4.838197554269257

In [13]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [14]:
# index single element in outermost dimension, first row
dataset[0]

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

In [15]:
dataset[0,:]

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

In [16]:
# index in reversed order in outermost dimension 
dataset[-1]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [17]:
dataset[-1,:]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [19]:
# index single element in two-dimensional data 
dataset[1,1]

97.10439252

In [20]:
# index in reversed order in two-dimensional data, the last element in the matrix
dataset[-1,-1]

100.07721494

In [21]:
# rows 1 and 2
dataset[1:3]

array([[ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286]])

In [22]:
# 2x2 subset of the data
dataset[:2,:2]

array([[ 99.14931546, 104.03852715],
       [ 92.02628776,  97.10439252]])

In [23]:
# last row with elements reversed
dataset[-1, ::-1]

array([100.07721494, 106.05042487,  98.75108352,  93.97853495,
        97.62787811, 104.51786419,  99.62387832,  94.11176915])

In [25]:
dataset[-1, :]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [26]:
# last 4 rows, every other element up to index 6
dataset[-5:-1,:6:2]

array([[ 96.76814836, 101.79132774,  98.29243952],
       [106.89005002, 102.26648279,  99.94318168],
       [ 99.80873105, 106.46476468, 100.69156231],
       [ 96.10020311, 100.80409326,  98.61325194]])

In [34]:
# create a dataset that fits the data
import pandas as pd
df = pd.DataFrame(np.random.randint(0, 100, size=(24, 24)), columns=list('ABCDEFGHIJKLMNOPQRSTWXYZ'))

In [35]:
df.head()

A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
0  88  80  38  41  35   5  14  55  21  19  ...  50  76  22  24  70  92   6   
1  47  49  93  45  73  64  38  98  21  56  ...  52  87   1  48  98  92  65   
2   7  88  40  30  92  68  98  34   0   0  ...  63  57  14  35   2  57   1   
3   3  70  20  46  56  65  93  40  82  54  ...  99  89   6  69  62  88  34   
4  80  48   5  65  83  13  15  78  96  18  ...  96  80  73  36  54  53  27   

    X   Y   Z  
0  33  37  66  
1  63   4  57  
2  35   9  53  
3  92  17  14  
4  22  43  16  

[5 rows x 24 columns]

In [36]:
np.hsplit(df, (3))

C:\Users\lorra\anaconda3\envs\dv_workshop\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


[     A   B   C   D   E   F   G   H
 0   88  80  38  41  35   5  14  55
 1   47  49  93  45  73  64  38  98
 2    7  88  40  30  92  68  98  34
 3    3  70  20  46  56  65  93  40
 4   80  48   5  65  83  13  15  78
 5   96  30  95  39  61  13  48  72
 6    7  27  91  18   5  57  44  67
 7   68  30  75  50  67  18   3  65
 8   19  60  27  48  90   4  35   4
 9    5  68  79  88  45  85  81  57
 10  21  95  57  44  75  92  70  43
 11  60  97  43  59  74  29  84  89
 12  84  48  59  77  31  67  26  46
 13  93  98   7  78  42  20  44  89
 14  10  19  82  97  84  16   0  82
 15  93  79  45  17  39  13  86  38
 16  19  77  62  27  97  19  68  49
 17  10  67  55  57  29  42  70  92
 18  38  70   0  80  84  44  80  66
 19  99  95   1  89  49  75  51  45
 20  48  17  44   7  88  37  18  58
 21   8   8  70  41  38  35  37  12
 22  80  79  26  68  10  65  25   0
 23  77   5  57  36  59  24  74  18,
      I   J   K   L   M   N   O   P
 0   21  19  73  88   2  66  50  76
 1   21  56  61  51  51  99

In [38]:
# split vertically in 2 equal lists
np.vsplit(df,(2))

C:\Users\lorra\anaconda3\envs\dv_workshop\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


[     A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
 0   88  80  38  41  35   5  14  55  21  19  ...  50  76  22  24  70  92   6   
 1   47  49  93  45  73  64  38  98  21  56  ...  52  87   1  48  98  92  65   
 2    7  88  40  30  92  68  98  34   0   0  ...  63  57  14  35   2  57   1   
 3    3  70  20  46  56  65  93  40  82  54  ...  99  89   6  69  62  88  34   
 4   80  48   5  65  83  13  15  78  96  18  ...  96  80  73  36  54  53  27   
 5   96  30  95  39  61  13  48  72  46  51  ...  78   6  21  10  29  88  95   
 6    7  27  91  18   5  57  44  67  74  53  ...  28  78  68  70  52  46  30   
 7   68  30  75  50  67  18   3  65  15  91  ...  30  74   9  67   8  72  95   
 8   19  60  27  48  90   4  35   4   9  51  ...  89  84  45  46  62  67  35   
 9    5  68  79  88  45  85  81  57  49  39  ...  48  47  29  50  40  22  93   
 10  21  95  57  44  75  92  70  43  23  95  ...  76  38  52  57  68  68  50   
 11  60  97  43  59  74  29  84  89  63 

In [42]:
# iterating over whole dataset (each value in each row)
for x in np.nditer(dataset):
    print(x)

99.14931546
104.03852715
107.43534677
97.85230675
98.74986914
98.80833412
96.81964892
98.56783189
92.02628776
97.10439252
99.32066924
97.24584816
92.9267508
92.65657752
105.7197853
101.23162942
95.66253664
95.17750125
90.93318132
110.18889465
98.80084371
105.95297652
98.37481387
106.54654286
91.37294597
100.96781394
100.40118279
113.42090475
105.48508838
91.6604946
106.1472841
95.08715803
101.20862522
103.5730309
100.28690912
105.85269352
93.37126331
108.57980357
100.79478953
94.20019732
102.80387079
98.29687616
93.24376389
97.24130034
89.03452725
96.2832753
104.60344836
101.13442416
106.71751618
102.97585605
98.45723272
100.72418901
106.39798503
95.46493436
94.35373179
106.83273763
96.02548256
102.82360856
106.47551845
101.34745901
102.45651798
98.74767493
97.57544275
92.5748759
105.30350449
92.87730812
103.19258339
104.40518318
101.29326772
100.85447132
101.2226037
106.03868807
110.44484313
93.87155456
101.5363647
97.65393524
92.75048583
101.72074646
96.96851209
103.29147111
101.3514

In [43]:
"""
iterating over the whole dataset with indices matching the position in the dataset
"""
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.724