### Exercise 1.02: Indexing, Slicing, Splitting, and Iterating

In [1]:
import numpy as np

In [2]:
dataset = np.genfromtxt('../Datasets/normal_distribution_splittable.csv', delimiter=',')

In [3]:
second_row = dataset[1]
np.mean(second_row)

96.90038836444445

In [4]:
last_row = dataset[-1]
np.mean(last_row)

100.18096645222221

In [5]:
np.mean(dataset)

100.11276252319443

In [6]:
# access the first value of the first row and the last value of the second last row
first_val_first_row = dataset[0][0]
np.mean(first_val_first_row)

99.14931546

In [7]:
first_val_first_row

99.14931546

In [8]:
last_val_second_last_row = dataset[-2, -1]
np.mean(last_val_second_last_row)

101.2226037

In [9]:
last_val_second_last_row

101.2226037

In [10]:
"""
slicing an intersection of 4 elements (2x2) of the first two rows
and the first two columns
"""
subsection_2x2 = dataset[1:3, 1:3]

In [11]:
np.mean(subsection_2x2)

95.63393608250001

In [12]:
# we want to have every other element of the fifth row
every_other_elem = dataset[4, ::2]
np.mean(every_other_elem)

98.35235805800001

In [13]:
# reverse the elements in a slice using negative numbers:
reversed_last_row = dataset[-1, ::-1]
np.mean(reversed_last_row)

100.18096645222222

In [17]:
hor_splits = np.hsplit(dataset,(3))
hor_splits[0].shape

(24, 3)

In [18]:
# split the first third into two equal parts vertically
ver_splits = np.vsplit(hor_splits[0],(2))
ver_splits

[array([[ 99.14931546, 104.03852715, 107.43534677],
        [ 92.02628776,  97.10439252,  99.32066924],
        [ 95.66253664,  95.17750125,  90.93318132],
        [ 91.37294597, 100.96781394, 100.40118279],
        [101.20862522, 103.5730309 , 100.28690912],
        [102.80387079,  98.29687616,  93.24376389],
        [106.71751618, 102.97585605,  98.45723272],
        [ 96.02548256, 102.82360856, 106.47551845],
        [105.30350449,  92.87730812, 103.19258339],
        [110.44484313,  93.87155456, 101.5363647 ],
        [101.3514185 , 100.37372248, 106.6471081 ],
        [ 97.21315663, 107.02874163, 102.17642112]]),
 array([[ 95.65982034, 107.22482426, 107.19119932],
        [100.39303522,  92.0108226 ,  97.75887636],
        [103.1521596 , 109.40523174,  93.83969256],
        [106.11454989,  88.80221141,  94.5081787 ],
        [ 96.78266211,  99.84251605, 104.03478031],
        [101.86186193, 103.61720152,  99.57859892],
        [ 97.49594839,  96.59385486, 104.63817694],
        [ 

In [19]:
print("Dataset", dataset.shape)
print("Subset", ver_splits[0].shape)

Dataset (24, 9)
Subset (12, 3)


In [20]:
# iterate over the whole dataset
curr_index = 0
for x in np.nditer(dataset):
    print(x, curr_index)
    curr_index += 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
101.34745901 8
92.02628776 9
97.10439252 10
99.32066924 11
97.24584816 12
92.9267508 13
92.65657752 14
105.7197853 15
101.23162942 16
93.87155456 17
95.66253664 18
95.17750125 19
90.93318132 20
110.18889465 21
98.80084371 22
105.95297652 23
98.37481387 24
106.54654286 25
107.22482426 26
91.37294597 27
100.96781394 28
100.40118279 29
113.42090475 30
105.48508838 31
91.6604946 32
106.1472841 33
95.08715803 34
103.40412146 35
101.20862522 36
103.5730309 37
100.28690912 38
105.85269352 39
93.37126331 40
108.57980357 41
100.79478953 42
94.20019732 43
96.10020311 44
102.80387079 45
98.29687616 46
93.24376389 47
97.24130034 48
89.03452725 49
96.2832753 50
104.60344836 51
101.13442416 52
97.62787811 53
106.71751618 54
102.97585605 55
98.45723272 56
100.72418901 57
106.39798503 58
95.46493436 59
94.35373179 60
106.83273763 61
100.07721494 62
96.02548256 63
102.82360856 64
106.475518

In [21]:
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(0, 8) 101.34745901
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(1, 8) 93.87155456
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(2, 8) 107.22482426
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(3, 8) 103.40412146
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(4, 8) 96.10020311
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.6034

In [22]:
# (5, 6) 104.60344836
dataset[5,6]

104.60344836

In [23]:
# create a dataset that fits the data
import pandas as pd
df = pd.DataFrame(np.random.randint(0, 100, size=(24, 24)), columns=list('ABCDEFGHIJKLMNOPQRSTWXYZ'))

In [25]:
df[df.A > 50]

A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
0   71  66  51  14  43  67  39  75  87  90  ...  23  85   3  43  92  44  97   
1   83   8  21  23   5  86  58  65  10   5  ...  11  74   7  77  21  62  62   
3   92  33  19  36  86  97  29  44  94  71  ...   3  59  94  73  69   2  44   
4   94  55  13  89  68  29  19  23  94  77  ...  48  44  48  90  22  72  27   
6   51   5   7  97  84  36  84  52  55  38  ...  38  76   1  13  53  40  40   
8   91  33  46  43  84  38  29  62  79  95  ...  68  44  66  20  65  63  23   
10  51  74  33  57  55  12   7  39  13  76  ...  27  83   8  59  60  34  31   
11  66  37  89  68  13  49  66  58  66  93  ...  11  64  98  61  81  84  42   
12  94   2  14  69   7  87  44  64  22  48  ...  26  65  22  12  80  65  35   
16  52  63  98  57  24  52  28  65  49  12  ...  13  89   1  18  53  48  46   
18  85  44  46   9  93  45  42  91  20   9  ...  59  63  79  46  80  18  28   
22  80  31  74  66  51  16  81  67  14  17  ...  19   1  26  73  75  69  92   

     X   Y   Z  
0   94  21  27  
1   31  28  41  
3   50  37  50  
4   80  68  62  
6   51  86  59  
8   49  18  14  
10  94  45  19  
11  51  92  11  
12  20  46  68  
16  11  18  54  
18  99   0  41  
22   3  75  23  

[12 rows x 24 columns]

In [30]:
df[df.A > 50][df.B > 50]

C:\Users\lorra\AppData\Local\Temp\ipykernel_32840\3450859088.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.A > 50][df.B > 50]


A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
0   71  66  51  14  43  67  39  75  87  90  ...  23  85   3  43  92  44  97   
4   94  55  13  89  68  29  19  23  94  77  ...  48  44  48  90  22  72  27   
10  51  74  33  57  55  12   7  39  13  76  ...  27  83   8  59  60  34  31   
16  52  63  98  57  24  52  28  65  49  12  ...  13  89   1  18  53  48  46   

     X   Y   Z  
0   94  21  27  
4   80  68  62  
10  94  45  19  
16  11  18  54  

[4 rows x 24 columns]

In [38]:
df2 = np.extract( (df < 3), df)

In [39]:
df2

array([0, 2, 2, 2, 1, 2, 1, 1, 0, 0, 1, 2, 2, 2, 1, 2])

In [40]:
# values bigger 5 and smaller 10
df[(df > 5) & (df < 10)]

A    B    C    D    E   F    G   H    I    J  ...   O    P    Q   R    S  \
0  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
1  NaN  8.0  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  7.0 NaN  NaN   
2  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
3  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
4  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
5  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  9.0  NaN  ... NaN  NaN  NaN NaN  NaN   
6  NaN  NaN  7.0  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
7  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
8  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
9  NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
10 NaN  NaN  NaN  NaN  NaN NaN  7.0 NaN  NaN  NaN  ... NaN  NaN  8.0 NaN  NaN   
11 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
12 NaN  NaN  NaN  NaN  7.0 NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
13 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
14 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
15 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  7.0   
16 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
17 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  9.0  ... NaN  NaN  NaN NaN  NaN   
18 NaN  NaN  NaN  9.0  NaN NaN  NaN NaN  NaN  9.0  ... NaN  NaN  NaN NaN  NaN   
19 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
20 NaN  6.0  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
21 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  7.0  NaN NaN  NaN   
22 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   
23 NaN  NaN  NaN  NaN  NaN NaN  NaN NaN  NaN  NaN  ... NaN  NaN  NaN NaN  NaN   

      T   W    X   Y    Z  
0   NaN NaN  NaN NaN  NaN  
1   NaN NaN  NaN NaN  NaN  
2   NaN NaN  NaN NaN  NaN  
3   NaN NaN  NaN NaN  NaN  
4   NaN NaN  NaN NaN  NaN  
5   NaN NaN  NaN NaN  NaN  
6   NaN NaN  NaN NaN  NaN  
7   NaN NaN  NaN NaN  NaN  
8   NaN NaN  NaN NaN  NaN  
9   NaN NaN  7.0 NaN  NaN  
10  NaN NaN  NaN NaN  NaN  
11  NaN NaN  NaN NaN  NaN  
12  NaN NaN  NaN NaN  NaN  
13  NaN NaN  NaN NaN  8.0  
14  NaN NaN  NaN NaN  NaN  
15  NaN NaN  NaN NaN  NaN  
16  NaN NaN  NaN NaN  NaN  
17  NaN NaN  NaN NaN  NaN  
18  NaN NaN  NaN NaN  NaN  
19  NaN NaN  NaN NaN  NaN  
20  NaN NaN  NaN NaN  NaN  
21  6.0 NaN  NaN NaN  NaN  
22  NaN NaN  NaN NaN  NaN  
23  NaN NaN  NaN NaN  NaN  

[24 rows x 24 columns]

In [43]:
# indices of values bigger
np.where(df > 5)

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9, 

In [44]:
# values sorted on last axis
np.sort(df)

array([[ 3, 10, 14, 21, 23, 23, 27, 33, 39, 43, 43, 44, 51, 66, 67, 71,
        75, 79, 85, 87, 90, 92, 94, 97],
       [ 5,  5,  7,  8, 10, 11, 21, 21, 23, 24, 28, 31, 41, 56, 58, 62,
        62, 65, 65, 74, 77, 83, 86, 87],
       [ 0,  2,  5,  5, 10, 10, 12, 29, 30, 32, 33, 33, 39, 44, 52, 67,
        68, 68, 72, 73, 74, 87, 89, 94],
       [ 2,  3, 19, 24, 29, 33, 36, 37, 44, 44, 50, 50, 59, 69, 69, 71,
        71, 73, 74, 86, 92, 94, 94, 97],
       [10, 13, 19, 22, 23, 27, 29, 44, 48, 48, 55, 62, 68, 68, 69, 72,
        72, 76, 77, 80, 89, 90, 94, 94],
       [ 2,  3,  9, 20, 23, 25, 31, 32, 37, 37, 37, 46, 51, 51, 57, 60,
        73, 78, 81, 82, 89, 90, 96, 98],
       [ 1,  3,  5,  7, 13, 36, 38, 38, 40, 40, 51, 51, 52, 53, 55, 59,
        71, 76, 79, 84, 84, 86, 97, 98],
       [17, 17, 20, 37, 37, 42, 42, 54, 55, 62, 63, 63, 64, 67, 69, 70,
        70, 71, 74, 80, 86, 91, 95, 99],
       [14, 15, 18, 20, 23, 29, 33, 38, 43, 44, 46, 49, 62, 63, 65, 66,
        68, 79, 84, 88, 

In [45]:
# values sorted on axis 0
np.sort(df, axis=0)

array([[ 3,  0,  5,  2,  5, 12,  7,  1,  4,  5,  2,  3,  0,  4,  3,  1,
         1, 12,  7,  2,  3,  3,  0,  8],
       [ 4,  2,  7,  9,  7, 16, 19, 19,  9,  9,  4, 10,  2, 11, 11,  7,
         1, 13, 13,  5,  5,  5, 10, 11],
       [ 5,  2, 10, 14, 13, 16, 28, 23, 10,  9, 10, 12, 13, 17, 11, 11,
         1, 18, 21,  6, 20,  7, 13, 12],
       [22,  2, 11, 17, 19, 24, 28, 27, 13, 12, 17, 12, 17, 23, 13, 14,
         2, 20, 22, 18, 23, 11, 15, 12],
       [28,  5, 13, 23, 24, 26, 29, 28, 14, 13, 26, 14, 20, 23, 19, 25,
         3, 22, 24, 25, 27, 17, 18, 14],
       [36,  6, 14, 36, 24, 29, 29, 39, 19, 17, 26, 15, 21, 24, 20, 29,
         7, 30, 35, 34, 28, 17, 18, 19],
       [37,  8, 19, 37, 32, 31, 33, 42, 20, 25, 27, 18, 24, 33, 23, 44,
         8, 31, 37, 36, 31, 20, 21, 23],
       [40, 31, 21, 43, 43, 36, 39, 44, 22, 34, 27, 20, 26, 35, 26, 44,
        10, 34, 53, 37, 33, 31, 21, 27],
       [42, 33, 33, 43, 51, 38, 42, 52, 27, 38, 31, 22, 29, 38, 27, 48,
        14, 43, 53, 40, 

In [46]:
# indices of values in sorted list
np.argsort(dataset)

array([[6, 3, 7, 4, 5, 0, 8, 1, 2],
       [0, 5, 4, 8, 1, 3, 2, 7, 6],
       [2, 1, 0, 6, 4, 5, 7, 8, 3],
       [0, 5, 7, 2, 1, 8, 4, 6, 3],
       [4, 7, 8, 2, 6, 0, 1, 3, 5],
       [4, 2, 5, 3, 8, 1, 7, 0, 6],
       [6, 5, 2, 8, 3, 1, 4, 0, 7],
       [8, 7, 0, 6, 5, 3, 4, 1, 2],
       [1, 8, 5, 6, 4, 2, 3, 0, 7],
       [4, 1, 6, 3, 8, 2, 5, 7, 0],
       [8, 7, 6, 5, 1, 3, 0, 4, 2],
       [4, 3, 0, 7, 2, 5, 6, 8, 1],
       [4, 6, 5, 0, 8, 7, 3, 2, 1],
       [1, 3, 8, 6, 2, 7, 0, 4, 5],
       [2, 5, 3, 4, 6, 0, 7, 8, 1],
       [1, 2, 3, 5, 6, 7, 8, 4, 0],
       [0, 8, 6, 1, 2, 7, 4, 5, 3],
       [5, 6, 3, 2, 0, 4, 1, 7, 8],
       [6, 5, 1, 0, 7, 8, 3, 2, 4],
       [8, 1, 0, 6, 4, 3, 2, 5, 7],
       [8, 7, 4, 2, 5, 6, 1, 0, 3],
       [7, 8, 0, 5, 4, 6, 1, 2, 3],
       [1, 5, 0, 6, 4, 2, 8, 7, 3],
       [4, 0, 3, 5, 1, 7, 2, 6, 8]], dtype=int64)