### 1. Replace Elements with numpy.where()

We'll use a 2 dimensional random array here, and only output the positive elements

In [4]:
import numpy as np

# Random initialization of a (2D array)
a = np.random.randn(2,3)
print (a)

[[ 0.08195344  0.12666454  1.0349408 ]
 [-0.04841144  1.62894323 -0.99378598]]


In [5]:
# b will be all elements of a whenever the condition holds true (i.e. only positive elements)
# Otherwise, set it as 0
b = np.where(a > 0, a, 0)
b

array([[0.08195344, 0.12666454, 1.0349408 ],
       [0.        , 1.62894323, 0.        ]])

In [7]:
import random
import numpy as np

a = np.random.randn(2, 3)
print(a)
b = np.where(a > 0)
print(b)


[[-0.6640197  -0.61972513  1.67230527]
 [ 0.82940929  0.91756865  1.05292563]]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [8]:
import numpy as np

a = np.arange(10)

b = np.where(a < 5, a, a * 10)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [9]:
import numpy as np

a = np.arange(12).reshape(3, 4)

b = np.arange(4).reshape(1, 4)

print(a)
print(b)

# Broadcasts (a < 5, a, and b * 10)
# of shape (3, 4), (3, 4) and (1, 4)
c = np.where(a < 5, a, b * 10)

print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4 10 20 30]
 [ 0 10 20 30]]


In [11]:
array_1D = np.array([1,2,3])
array_1D

array([1, 2, 3])

In [12]:
column_array_2D = array_1D.reshape((3,1))
column_array_2D

array([[1],
       [2],
       [3]])

In [13]:
my_column_array_2D = array_1D.reshape((-1,1))
my_column_array_2D

array([[1],
       [2],
       [3]])

In [14]:
row_array_2D = array_1D.reshape((1,3))
row_array_2D

array([[1, 2, 3]])